name: Compile and Upload Resume to GitHub Pages
on:
    push:
        branches:
            - "main"
        paths:
            - "resume.tex"
            - "index.html"
            - ".github/workflows/**"
    pull_request:
        branches:
            - "main"
        paths:
            - "resume.tex"
            - "index.html"
            - ".github/workflows/**"

jobs:
    build_latex:
        runs-on: ubuntu-latest
        container:
            image: danteev/texlive:latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3
              with:
                  persist-credentials: false

            - name: Compile LaTeX document
              uses: xu-cheng/latex-action@v2
              with:
                  root_file: resume.tex
                  latexmk_use_xelatex: true

            - name: Post Processing
              run: |
                  mkdir build 
                  cp *.pdf build/ 
                  cp index.html build/
                  
            - name: Git add
              run:  |
                  git config --global --add safe.directory /__w/resume/resume
                  git add resume.pdf
              
            - name: Deploy to GitHub Pages 🚀
              uses: JamesIves/github-pages-deploy-action@v4
              with:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  BRANCH: gh-pages
                  FOLDER: build
                  CLEAN: true